UPDATE `sbasvuru` SET iso900115varyok=0 where iso900115varyok is null;
UPDATE `sbasvuru` SET iso900115varyok=0 where iso900115varyok="";
UPDATE `sbasvuru` SET iso900115varyok=1 where iso900115varyok="X";
UPDATE `sbasvuru` SET iso1400115varyok=0 where iso1400115varyok is null;
UPDATE `sbasvuru` SET iso1400115varyok=0 where iso1400115varyok="";
UPDATE `sbasvuru` SET iso1400115varyok=1 where iso1400115varyok="X";
UPDATE `sbasvuru` SET iso2200018varyok=0 where iso2200018varyok is null;
UPDATE `sbasvuru` SET iso2200018varyok=0 where iso2200018varyok="";
UPDATE `sbasvuru` SET iso2200018varyok=1 where iso2200018varyok="X";
UPDATE `sbasvuru` SET iso4500118varyok=0 where iso4500118varyok is null;
UPDATE `sbasvuru` SET iso4500118varyok=0 where iso4500118varyok="";
UPDATE `sbasvuru` SET iso4500118varyok=1 where iso4500118varyok="X";
UPDATE `sbasvuru` SET iso5000118varyok=0 where iso5000118varyok is null;
UPDATE `sbasvuru` SET iso5000118varyok=0 where iso5000118varyok="";
UPDATE `sbasvuru` SET iso5000118varyok=1 where iso5000118varyok="X";
UPDATE `sbasvuru` SET helalvaryok=0 where helalvaryok is null;
UPDATE `sbasvuru` SET helalvaryok=0 where helalvaryok="";
UPDATE `sbasvuru` SET helalvaryok=1 where helalvaryok="X";
UPDATE `sbasvuru` SET iso27001varyok=0 where iso27001varyok is null;
UPDATE `sbasvuru` SET iso27001varyok=0 where iso27001varyok="";
UPDATE `sbasvuru` SET iso27001varyok=1 where iso27001varyok="X";
UPDATE `sbasvuru` SET oicsmiik6varyok=0 where oicsmiik6varyok is null;
UPDATE `sbasvuru` SET oicsmiik6varyok=0 where oicsmiik6varyok="";
UPDATE `sbasvuru` SET oicsmiik6varyok=1 where oicsmiik6varyok="X";
UPDATE `sbasvuru` SET oicsmiik9varyok=0 where oicsmiik9varyok is null;
UPDATE `sbasvuru` SET oicsmiik9varyok=0 where oicsmiik9varyok="";
UPDATE `sbasvuru` SET oicsmiik9varyok=1 where oicsmiik9varyok="X";
UPDATE `sbasvuru` SET oicsmiik171varyok=0 where oicsmiik171varyok is null;
UPDATE `sbasvuru` SET oicsmiik171varyok=0 where oicsmiik171varyok="";
UPDATE `sbasvuru` SET oicsmiik171varyok=1 where oicsmiik171varyok="X";
UPDATE `sbasvuru` SET oicsmiik24varyok=0 where oicsmiik24varyok is null;
UPDATE `sbasvuru` SET oicsmiik24varyok=0 where oicsmiik24varyok="";
UPDATE `sbasvuru` SET oicsmiik24varyok=1 where oicsmiik24varyok="X";
UPDATE `sbasvuru` SET oicsmiik23varyok=0 where oicsmiik23varyok is null;
UPDATE `sbasvuru` SET oicsmiik23varyok=0 where oicsmiik23varyok="";
UPDATE `sbasvuru` SET oicsmiik23varyok=1 where oicsmiik23varyok="X";
UPDATE `sbasvuru` SET sahasayisi22=0 where sahasayisi22="";
UPDATE `sbasvuru` SET sahasayisi22=0 where sahasayisi22="-";
UPDATE `sbasvuru` SET taseroncalisansayisi=0 where taseroncalisansayisi="";
UPDATE `sbasvuru` SET taseroncalisansayisi=0 where taseroncalisansayisi="-";
UPDATE `sbasvuru` SET tamzamanlicalisansayisi=0 where tamzamanlicalisansayisi="";
UPDATE `sbasvuru` SET tamzamanlicalisansayisi=0 where tamzamanlicalisansayisi="-";
UPDATE `sbasvuru` SET yarizamanlicalisansayisi=0 where yarizamanlicalisansayisi="";
UPDATE `sbasvuru` SET yarizamanlicalisansayisi=0 where yarizamanlicalisansayisi="-";
UPDATE `sbasvuru` SET toplamcalisansayisi=0 where toplamcalisansayisi="";
UPDATE `sbasvuru` SET toplamcalisansayisi=0 where toplamcalisansayisi="-";
UPDATE `sbasvuru` SET gecicicalisansayisi=0 where gecicicalisansayisi="";
UPDATE `sbasvuru` SET gecicicalisansayisi=0 where gecicicalisansayisi="-";
UPDATE `sbasvuru` SET vasifsizcalisansayisi=0 where vasifsizcalisansayisi="";
UPDATE `sbasvuru` SET vasifsizcalisansayisi=0 where vasifsizcalisansayisi="-";
UPDATE `sbasvuru` SET vardiyalicalisansayisi=0 where vardiyalicalisansayisi="";
UPDATE `sbasvuru` SET vardiyalicalisansayisi1=0 where vardiyalicalisansayisi1="";
UPDATE `sbasvuru` SET vardiyalicalisansayisi2=0 where vardiyalicalisansayisi2="";
UPDATE `sbasvuru` SET `faaliyetadicalsay1`=0 where `faaliyetadicalsay1`="";
UPDATE `sbasvuru` SET `faaliyetadicalsay1`=0 where `faaliyetadicalsay1`="-";
UPDATE `sbasvuru` SET `faaliyetadicalsay2`=0 where `faaliyetadicalsay2`="";
UPDATE `sbasvuru` SET `faaliyetadicalsay2`=0 where `faaliyetadicalsay2`="-";
UPDATE `sbasvuru` SET `faaliyetadicalsay3`=0 where `faaliyetadicalsay3`="";
UPDATE `sbasvuru` SET `faaliyetadicalsay3`=0 where `faaliyetadicalsay3`="-";
UPDATE `sbasvuru` SET `faaliyetadicalsay4`=0 where `faaliyetadicalsay4`="";
UPDATE `sbasvuru` SET `faaliyetadicalsay4`=0 where `faaliyetadicalsay4`="-";
UPDATE `sbasvuru` SET `faaliyetadicalsay5`=0 where `faaliyetadicalsay5`="";
UPDATE `sbasvuru` SET `faaliyetadicalsay5`=0 where `faaliyetadicalsay5`="-";
UPDATE `sbasvuru` SET `faaliyetadicalsay6`=0 where `faaliyetadicalsay6`="";
UPDATE `sbasvuru` SET `faaliyetadicalsay6`=0 where `faaliyetadicalsay6`="-";
UPDATE `sbasvuru` SET `subevard11`=0 where `subevard11`="";
UPDATE `sbasvuru` SET `subevard12`=0 where `subevard12`="";
UPDATE `sbasvuru` SET `subevard13`=0 where `subevard13`="";
UPDATE `sbasvuru` SET `subevard21`=0 where `subevard21`="";
UPDATE `sbasvuru` SET `subevard22`=0 where `subevard22`="";
UPDATE `sbasvuru` SET `subevard23`=0 where `subevard23`="";
UPDATE `sbasvuru` SET `subevard31`=0 where `subevard31`="";
UPDATE `sbasvuru` SET `subevard32`=0 where `subevard32`="";
UPDATE `sbasvuru` SET `subevard33`=0 where `subevard33`="";
UPDATE `sbasvuru` SET `yonetimsistemsertifikasi`=0 where `yonetimsistemsertifikasi`="";
UPDATE `sbasvuru` SET `yonetimsistemsertifikasi`=0 where `yonetimsistemsertifikasi`="-";
UPDATE `sbasvuru` SET `yonetimsistemsertifikasi`=0 where `yonetimsistemsertifikasi`="HAYIR";
UPDATE `sbasvuru` SET `yonetimsistemsertifikasi`=1 where `yonetimsistemsertifikasi`<>"EVET";
UPDATE `sbasvuru` SET `yonetimsistemsertifikasi`=1 where `yonetimsistemsertifikasi`="EVET";
UPDATE `sbasvuru` SET `helalurunsayisi`=0 where `helalurunsayisi`="";
UPDATE `sbasvuru` SET `helalurunsayisi`=0 where `helalurunsayisi`="-";
UPDATE `sbasvuru` SET `haccpcalismasisayisi`=0 where `haccpcalismasisayisi`="";
UPDATE `sbasvuru` SET `haccpcalismasisayisi`=0 where `haccpcalismasisayisi`="-";
UPDATE `sbasvuru` SET `tumvardayni`=0 where `tumvardayni`="";
UPDATE `sbasvuru` SET `tumvardayni`=0 where `tumvardayni`="-";
UPDATE `sbasvuru` SET `tumvardayni`=0 where `tumvardayni`="HAYIR";
UPDATE `sbasvuru` SET `tumvardayni`=1 where `tumvardayni`="EVET";
UPDATE `sbasvuru` SET `enerjikaynaksayisi`=0 where `enerjikaynaksayisi`="";
UPDATE `sbasvuru` SET `enerjikaynaksayisi`=0 where `enerjikaynaksayisi`="-";
UPDATE `sbasvuru` SET `oeksayisi`=0 where `oeksayisi`="";
UPDATE `sbasvuru` SET `oeksayisi`=0 where `oeksayisi`="-";
UPDATE `sbasvuru` SET `havuzsayisi`=0 where `havuzsayisi`="";
UPDATE `sbasvuru` SET `havuzsayisi`=0 where `havuzsayisi`="-";
UPDATE `sbasvuru` SET `mutfaksayisi`=0 where `mutfaksayisi`="";
UPDATE `sbasvuru` SET `mutfaksayisi`=0 where `mutfaksayisi`="-";
UPDATE `sbasvuru` SET `odasayisi`=0 where `odasayisi`="";
UPDATE `sbasvuru` SET `odasayisi`=0 where `odasayisi`="-";
UPDATE `sbasvuru` SET `ayniisiyapansayisi`=0 where `ayniisiyapansayisi`="";
UPDATE `sbasvuru` SET `ayniisiyapansayisi`=0 where `ayniisiyapansayisi`="-";
UPDATE `sbasvuru` SET `bgyscalisansayisi`=0 where `bgyscalisansayisi`="";
UPDATE `sbasvuru` SET `bgyscalisansayisi`=0 where `bgyscalisansayisi`="-";
UPDATE `sbasvuru` SET `enyscalisansayisi`=0 where `enyscalisansayisi`="";
UPDATE `sbasvuru` SET `enyscalisansayisi`=0 where `enyscalisansayisi`="-";
UPDATE `sbasvuru` SET `helalkkn`=0 where `helalkkn`="";
UPDATE `sbasvuru` SET `helalkkn`=0 where `helalkkn`="-";
UPDATE `sbasvuru` SET `haccpcalismasisayisismiic`=0 where `haccpcalismasisayisismiic`="";
UPDATE `sbasvuru` SET `haccpcalismasisayisismiic`=0 where `haccpcalismasisayisismiic`="-";
UPDATE `sbasvuru` SET `aracsayisi`=0 where `aracsayisi`="";
UPDATE `sbasvuru` SET `aracsayisi`=0 where `aracsayisi`="-";
