UPDATE `splanlar` SET entegreysvarmi=0 where entegreysvarmi="";
UPDATE `splanlar` SET entegreysvarmi=0 where entegreysvarmi="-";
UPDATE `splanlar` SET entegreysvarmi=1 where entegreysvarmi="X";
UPDATE `splanlar` SET entegreysvarmi=1 where entegreysvarmi="Var";
UPDATE `splanlar` SET entegreysvarmi=0 where entegreysvarmi="Yok";
UPDATE `splanlar` SET entegreysvarmi=0 where entegreysvarmi="HAYIR";
UPDATE `splanlar` SET entegreysvarmi=1 where entegreysvarmi="EVET";
UPDATE `splanlar` SET iso9001indart="0" where iso9001indart="";
UPDATE `splanlar` SET iso9001hamsure="0" where iso9001hamsure="";
UPDATE `splanlar` SET iso9001hamsure="0" where iso9001hamsure IS NULL;
UPDATE `splanlar` SET iso14001hamsure="0" where iso14001hamsure="";
UPDATE `splanlar` SET iso14001hamsure="0" where iso14001hamsure IS NULL;
UPDATE `splanlar` SET iso14001indart="0" where iso14001indart="";
UPDATE `splanlar` SET iso14001indart="0" where iso45001hamsure IS NULL;
UPDATE `splanlar` SET iso45001hamsure="0" where iso45001hamsure="";
UPDATE `splanlar` SET iso45001hamsure="0" where iso45001hamsure IS NULL;
UPDATE `splanlar` SET iso45001indart="0" where iso45001indart="";
UPDATE `splanlar` SET iso50001hamsure="0" where iso50001hamsure="";
UPDATE `splanlar` SET iso50001hamsure="0" where iso50001hamsure IS NULL;
UPDATE `splanlar` SET iso50001indart="0" where iso50001indart="";
UPDATE `splanlar` SET iso27001hamsure="0" where iso27001hamsure="";
UPDATE `splanlar` SET iso27001hamsure="0" where iso27001hamsure IS NULL;
UPDATE `splanlar` SET iso27001indart="0" where iso27001indart="";
UPDATE `splanlar` SET iso22000normalsure="0" where iso22000normalsure="";
UPDATE `splanlar` SET iso22000normalsure="0" where iso22000normalsure IS NULL;
UPDATE `splanlar` SET iso22000indart="0" where iso22000indart="";
UPDATE `splanlar` SET oicsmiicnormalsure="0" where oicsmiicnormalsure="";
UPDATE `splanlar` SET oicsmiicnormalsure="0" where oicsmiicnormalsure IS NULL;
UPDATE `splanlar` SET oicsmiicindart="0" where oicsmiicindart="";
UPDATE `splanlar` SET oicsmiicindart="0" where oicsmiicindart IS NULL;
UPDATE `splanlar` SET oicsmiicentindart="0" where oicsmiicentindart IS NULL;
UPDATE `splanlar` SET oicsmiickalansure="0" where oicsmiickalansure IS NULL;
UPDATE `splanlar` SET oicsmiica1sure="0" where oicsmiica1sure IS NULL;
UPDATE `splanlar` SET oicsmiica2sure="0" where oicsmiica2sure IS NULL;
UPDATE `splanlar` SET oicsmiicgsure="0" where oicsmiicgsure IS NULL;
UPDATE `splanlar` SET oicsmiicybsure="0" where oicsmiicybsure IS NULL;
UPDATE `splanlar` SET asama='ilkplan' where asama="BAŞVURU";
UPDATE `splanlar` SET asama='ilkplan' where asama="";
UPDATE `splanlar` SET asama='ilkplan' where asama IS NULL;
UPDATE `splanlar` SET belgecevrimi=1 where belgecevrimi is null;
UPDATE `splanlar` SET belgecevrimi=1 where belgecevrimi="";